# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
    version: 2.1

    jobs: # Jobs declared to be called in workflows
        print_name:
            parameters:
              variable: 
                type: string
            docker:
              - image: cimg/base:stable # This image can be different from the one declared in other job
            steps:
              - checkout
              - run: echo <<parameters.variable>> 
    
    workflows:
        display: # workflow name
            jobs:
              - print_name:
                  name: 'Job1'
                  variable: 'Hellow'
              - print_name:
                  name: 'Job2'
                  variable: 'World'
                  requires:
                    - Job1


              
