export interface IBooks {
  [books: string]: any;
}

export const BOOKS: IBooks = [
  // JavaScript
  {
    category: 'javascript',
    name: 'Eloquent Javascript A Modern Introduction to Programming',
    author: 'Marijn Haverbeke',
    year: '2018',
    pages: '447',
    format: 'PDF',
    downloadLink: 'https://bit.ly/35wKZPF',
    buyLink: 'https://amzn.to/3bSNm0l',
    description: 'Eloquent JavaScript dives into the JavaScript language to show programmers how to write elegant, effective JavaScript code. Like any good programming book,Eloquent JavaScriptbegins with fundamentals--variables, control structures, functions, and data structures--then moves on to complex topics like object-oriented programming and regular expressions',
    image: 'https://covers.zlibcdn2.com/covers299/books/e0/16/5a/e0165acb1767639826cf43eb5fab00e9.jpg',
  },
  {
    category: 'javascript',
    name: 'Learning JavaScript Design Patterns',
    author: 'Addy Osmani',
    year: '2012',
    pages: '199',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Zt7bq7',
    buyLink: 'https://amzn.to/3khG0X1',
    description: 'If you want to write beautiful, structured, and maintainable javascript code, this guide shows you how to apply both classical and modern design patterns to the language. The patterns in this book provide reusable code solutions to common problems in software design, and give you a shared vocabulary for describing solutions to others',
    image: 'https://covers.zlibcdn2.com/covers299/books/08/f6/16/08f6168945c836449f3e40e6c170ad67.jpg',
  },
  // JavaScript

  // Java
  {
    category: 'java',
    name: 'Java: The Complete Reference, Eleventh Edition',
    author: 'Herbert Schildt',
    year: '2019',
    pages: '1882',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2RzMTXL',
    buyLink: 'https://amzn.to/35s1ZXk',
    description: 'Fully updated for Java SE 11, Java: The Complete Reference, Eleventh Edition explains how to develop, compile, debug, and run Java programs. Best-selling programming author Herb Schildt covers the entire Java language, including its syntax, keywords, and fundamental programming principles. You’ll also find information on key portions of the Java API library, such as I/O, the Collections Framework, the stream library, and the concurrency utilities. Swing, JavaBeans, and servlets are examined and numerous examples demonstrate Java in action. Of course, the very important module system is discussed in detail. This Oracle Press resource also offers an introduction to JShell, Java’s interactive programming tool. Best of all, the book is written in the clear, crisp, uncompromising style that has made Schildt the choice of millions worldwide.',
    image: 'https://covers.zlibcdn2.com/covers299/books/7f/b0/e5/7fb0e58e87aef95feae8c9d3a986a0a7.jpg',
  },
  {
    category: 'java',
    name: 'Head First Java, 2nd Edition',
    author: 'Kathy Sierra',
    year: '2005',
    pages: '722',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3kbsSTu',
    buyLink: 'https://amzn.to/3misNze',
    description: 'Learning a complex new language is no easy task especially when it s an object-oriented computer programming language like Java. You might think the problem is your brain. It seems to have a mind of its own, a mind that doesn\'t always want to take in the dry, technical stuff you\'re forced to study. The fact is your brain craves novelty. It\'s constantly searching, scanning, waiting for something unusual to happen',
    image: 'https://covers.zlibcdn2.com/covers299/books/d5/be/db/d5bedbe6b001445ebb3851500fd19fb3.jpg',
  },
  {
    category: 'java',
    name: 'Java for Absolute Beginners',
    author: 'Iuliana Cosmina',
    year: '2019',
    pages: '623',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2RnxwkY',
    buyLink: 'https://amzn.to/2Zu4m88',
    description: 'Write your first code in Java using simple, step-by-step examples that model real-word objects and events, making learning easy. With this book you’ll be able to pick up the concepts without fuss. Java for Absolute Beginners teaches Java development in language anyone can understand, giving you the best possible start. You’ll see clear code descriptions and layout so that you can get your code running as soon as possible. After reading this book, you\'ll come away with the basics to get started writing programs in Java.',
    image: 'https://covers.zlibcdn2.com/covers299/books/0d/b0/f2/0db0f2eae168c600917807d193abdf4a.jpg',
  },
  // Java

  // Python
  {
    category: 'python',
    name: 'Python Basics: A Self-Teaching Introduction',
    author: 'H. Bhasin',
    year: '2019',
    pages: '566',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3kd9c1p',
    buyLink: 'https://amzn.to/2FpLQab',
    description: 'This book is designed for use as a primary introduction to Python and can be used as an introductory text or as a resource for professionals in industry. The book has been divided into four sections. The first section deals with the language fundamentals, primarily the procedural part of the language, the second introduces the object-oriented paradigms, the third section deals with data structures, and the last is devoted to advanced topics like handling multi-dimensional arrays using NumPy and visualization using Matplotlib. Regular expressions and multi-threading have been introduced in the appendices.',
    image: 'https://covers.zlibcdn2.com/covers299/books/f0/d3/6d/f0d36d571089b7f21c8e4a117b0440f5.jpg',
  },
  {
    category: 'python',
    name: 'Learning Python, 5th Edition',
    author: 'Mark Lutz',
    year: '2013',
    pages: '1600',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33i8b1a',
    buyLink: 'https://amzn.to/2ZxQ4Dn',
    description: 'Get a comprehensive, in-depth introduction to the core Python language with this hands-on book. Based on author Mark Lutz’s popular training course, this updated fifth edition will help you quickly write efficient, high-quality code with Python. It’s an ideal way to begin, whether you’re new to programming or a professional developer versed in other languages.',
    image: 'https://covers.zlibcdn2.com/covers299/books/2e/3b/7c/2e3b7c8e0d2f4d71d4b0753f62458ff1.jpg',
  },
  // Python

  // SQL
  {
    category: 'sql',
    name: 'SQL for Dummies',
    author: 'Allen G. Taylor',
    year: '2019',
    pages: '515',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3kbnZd4',
    buyLink: 'https://amzn.to/2ZzQIjP',
    description: 'SQL is the international standard database language used to create, access, manipulate, maintain, and store information in relational database management systems (DBMS) such as Access, Oracle, SQL Server, and MySQL. SQL adds powerful data manipulation and retrieval capabilities to conventional languages—and this book shows you how to harness the core element of relational databases with ease.',
    image: 'https://covers.zlibcdn2.com/covers299/books/6f/b8/d8/6fb8d87d7fb4865674245ff408354bda.jpg',
  },
  {
    category: 'sql',
    name: 'Practical SQL: A Beginner’s Guide to Storytelling with Data',
    author: 'DeBarros Anthony',
    year: '2018',
    pages: '527',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3hsCYO7',
    buyLink: 'https://amzn.to/3irlAdD',
    description: 'Practical SQL is an approachable and fast-paced guide to SQL (Structured Query Language), the standard programming language for defining, organizing, and exploring data in relational databases. The book focuses on using SQL to find the story your data tells, with the popular open-source database PostgreSQL and the pgAdmin interface as its primary tools',
    image: 'https://covers.zlibcdn2.com/covers299/books/b9/a9/b7/b9a9b788cf8f7b2d0888aa414462373e.jpg',
  },
  // SQL

  // Data structure & Algorithms
  {
    category: 'data structure & algorithms',
    name: 'Introduction to algorithms',
    author: 'Thomas Cormen',
    year: '2009',
    pages: '1313',
    format: 'PDF',
    downloadLink: 'https://bit.ly/35wua7r',
    buyLink: 'https://amzn.to/2GMON4T',
    description: 'In the preface, the authors write about how the book was written to be comprehensive and useful in both teaching and professional environments. Each chapter focuses on an algorithm, and discusses its design techniques and areas of application. Instead of using a specific programming language, the algorithms are written in pseudocode. The descriptions focus on the aspects of the algorithm itself, its mathematical properties, and emphasize efficiency',
    image: 'https://covers.zlibcdn2.com/covers299/books/ed/37/2a/ed372ab968c3d988e0490962553aa3cf.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'The Algorithm Design Manual',
    author: 'Thomas Cormen',
    year: '2013',
    pages: '237',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33pOXH5',
    buyLink: 'https://amzn.to/2DULDej',
    description: 'Have you ever wondered how your GPS can find the fastest way to your destination, selecting one route from seemingly countless possibilities in mere seconds? How your credit card account number is protected when you make a purchase over the Internet? The answer is algorithms. And how do these mathematical formulations translate themselves into your GPS, your laptop, or your smart phone? This book offers an engagingly written guide to the basics of computer algorithms. In Algorithms Unlocked, Thomas Cormen―coauthor of the leading college textbook on the subject―provides a general explanation, with limited mathematics, of how algorithms enable computers to solve problems.',
    image: 'https://covers.zlibcdn2.com/covers299/books/de/d6/55/ded655a8c87eda65c81f064aade1f901.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'The Algorithm Design Manual',
    author: 'Steven S. Skiena',
    year: '2008',
    pages: '730',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2RlWscr',
    buyLink: 'https://amzn.to/3kq8mPh',
    description: 'The reader-friendly Algorithm Design Manual provides straightforward access to combinatorial algorithms technology, stressing design over analysis. The first part, Techniques, provides accessible instruction on methods for designing and analyzing computer algorithms. The second part, Resources, is intended for browsing and reference, and comprises the catalog of algorithmic resources, implementations and an extensive bibliography.',
    image: 'https://covers.zlibcdn2.com/covers299/books/00/cb/81/00cb810a4b852c9631b47fb6de8efad0.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'Algorithms: Part II, 4th Edition',
    author: 'Robert Sedgewick',
    year: '2014',
    pages: '950',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mkq2xa',
    buyLink: 'https://amzn.to/35AlQ6C',
    description: 'The reader-friendly Algorithm Design Manual provides straightforward access to combinatorial algorithms technology, stressing design over analysis. The first part, Techniques, provides accessible instruction on methods for designing and analyzing computer algorithms. The second part, Resources, is intended for browsing and reference, and comprises the catalog of algorithmic resources, implementations and an extensive bibliography.',
    image: 'https://covers.zlibcdn2.com/covers299/books/d3/07/7a/d3077abbf3e55579b7973d04da812939.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'Data Structures & Algorithms in Java',
    author: 'Robert Lafore',
    year: '1998',
    pages: '526',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3k8rgcY',
    buyLink: 'https://amzn.to/35w62lj',
    description: 'Not filled with with obtuse mathematics and difficult proofs, MWSS:Data Structures and Algorithms in Java removes the mystique from DS&A. It does this in two ways. First, the text is written in a straightforward style, making it accessible to anyone. Second, unique new Java demonstration programs, called "Workshop Applets," are provided with the book',
    image: 'https://covers.zlibcdn2.com/covers299/books/50/aa/05/50aa051a399071ca6ac7e837fb7f1be8.jpg',
  },
  {
    category: 'data structure & algorithms',
    name: 'Graph algorithms',
    author: 'Shimon Even',
    year: '2012',
    pages: '204',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2ZxC3FQ',
    buyLink: 'https://amzn.to/2ZAsvKj',
    description: '"Shimon Even\'s Graph Algorithms, published in 1979, was a seminal introductory book on algorithms read by everyone engaged in the field. This thoroughly revised second edition, with a foreword by Richard M. Karp and notes by Andrew V. Goldberg, continues the exceptional presentation from the first edition and explains algorithms in a formal but simple language with a direct and intuitive presentation',
    image: 'https://covers.zlibcdn2.com/covers299/books/a4/50/77/a45077516b7bb8d941708255fbf7d4ea.gif',
  },
  {
    category: 'data structure & algorithms',
    name: 'Graphs, Networks and Algorithms',
    author: 'Dieter Jungnickel.',
    year: '2013',
    pages: '615',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2RkIJTg',
    buyLink: 'https://amzn.to/3hoercN',
    description: 'The book is a first class textbook and seems to be indispensable for everybody who has to teach combinatorial optimization. It is very helpful for students, teachers, and researchers in this area. The author finds a striking synthesis of nice and interesting mathematical results and practical applications',
    image: 'https://covers.zlibcdn2.com/covers299/books/4c/de/c4/4cdec4f61b2a3525960b488962c14778.jpg',
  },
  // Data structure & Algorithms

  // Architecture
  {
    category: 'architecture',
    name: 'Clean Architecture: A Craftsman’s Guide to Software Structure and Design',
    author: 'Robert C. Martin',
    year: '2017',
    pages: '429',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Zw1uaI',
    buyLink: 'https://amzn.to/2Fv5e5h',
    description: 'Building upon the success of best-sellers The Clean Coder and Clean Code, legendary software craftsman Robert C. "Uncle Bob" Martin shows how to bring greater professionalism and discipline to application architecture and design.',
    image: 'https://covers.zlibcdn2.com/covers299/books/b1/c9/42/b1c94251908069df0a3dbe2462f52cdd.jpg',
  },
  {
    category: 'architecture',
    name: 'Computer Architecture, Sixth Edition: A Quantitative Approach',
    author: 'David A. Patterson',
    year: '2017',
    pages: '936',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mh2tWb',
    buyLink: 'https://amzn.to/3ir5Do7',
    description: 'Computer Architecture: A Quantitative Approach, Sixth Edition has been considered essential reading by instructors, students and practitioners of computer design for over 20 years. The sixth edition of this classic textbook is fully revised with the latest developments in processor and system architecture. It now features examples from the RISC-V (RISC Five) instruction set architecture, a modern RISC instruction set developed and designed to be a free and openly adoptable standard. It also includes a new chapter on domain-specific architectures and an updated chapter on warehouse-scale computing that features the first public information on Google\'s newest WSC.',
    image: 'https://covers.zlibcdn2.com/covers299/books/58/73/4d/58734dae75228cd8ccf1be995da2893a.jpg',
  },
  // Architecture

  // Design patterns
  {
    category: 'design patterns',
    name: 'Head First Design Patterns',
    author: 'Eric Freeman',
    year: '2014',
    pages: '867',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3ms9WBY',
    buyLink: 'https://amzn.to/2DWsCYZ',
    description: 'At any given moment, someone struggles with the same software design problems you have. And, chances are, someone else has already solved your problem. This edition of Head First Design Patterns—now updated for Java 8—shows you the tried-and-true, road-tested patterns used by developers to create functional, elegant, reusable, and flexible software. By the time you finish this book, you’ll be able to take advantage of the best design practices and experiences of those who have fought the beast of software design and triumphed.',
    image: 'https://covers.zlibcdn2.com/covers299/books/8c/26/dc/8c26dcd40152ee5088314b1c62db48cb.jpg',
  },
  {
    category: 'design patterns',
    name: 'Building Structures Illustrated: Patterns, Systems, and Design',
    author: 'Francis D. K. Ching',
    year: '2013',
    pages: '354',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mlLrX8',
    buyLink: 'https://amzn.to/3hrEeRF',
    description: 'Structures are an essential element of the building process, yet one of the most difficult concepts for architects to grasp. While structural engineers do the detailed consulting work for a project, architects should have enough knowledge of structural theory and analysis to design a building. Building Structures Illustrated takes a new approach to structural design, showing how structural systems of a building—such as an integrated assembly of elements with pattern, proportions, and scale—are related to the fundamental aspects of architectural design',
    image: 'https://covers.zlibcdn2.com/covers299/books/cb/b2/f6/cbb2f6cc498af0a2ae57e5be6716758b.jpg',
  },
  // Design patterns

  // Networks
  {
    category: 'networks',
    name: 'Networks',
    author: 'Mark Newman',
    year: '2018',
    pages: '800',
    format: 'PDF',
    downloadLink: 'https://bit.ly/35wwMSN',
    buyLink: 'https://amzn.to/2RlY99T',
    description: 'The study of networks, including computer networks, social networks, and biological networks, has attracted enormous interest in the last few years. The rise of the Internet and the wide availability of inexpensive computers have made it possible to gather and analyze network data on an unprecedented scale, and the development of new theoretical tools has allowed us to extract knowledge from networks of many different kinds. The study of networks is broadly interdisciplinary and central developments have occurred in many fields, including mathematics, physics, computer and information sciences, biology, and the social sciences. This book brings together the most important breakthroughs in each of these fields and presents them in a coherent fashion, highlighting the strong interconnections between work in different areas.',
    image: 'https://covers.zlibcdn2.com/covers299/books/52/26/dd/5226dd61a8e53e82d123f4831acaf53b.jpg',
  },
  {
    category: 'networks',
    name: 'Computer Networking: A Top-Down Approach',
    author: 'Keith Ross',
    year: '2016',
    pages: '864',
    format: 'PDF',
    downloadLink: 'https://bit.ly/35vY8IP',
    buyLink: 'https://amzn.to/3msaxnc',
    description: 'Unique among computer networking texts, the Seventh Edition of the popular Computer Networking: A Top Down Approach builds on the author’s long tradition of teaching this complex subject through a layered approach in a “top-down manner.” The text works its way from the application layer down toward the physical layer, motivating readers by exposing them to important concepts early in their study of networking',
    image: 'https://covers.zlibcdn2.com/covers299/books/25/b0/96/25b0960fd42a492a64082880678a76af.jpg',
  },
  {
    category: 'networks',
    name: 'Computer Networks',
    author: 'Andrew Tanenbaum',
    year: '2013',
    pages: '962',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33rE5Z9',
    buyLink: 'https://amzn.to/2ZzZ0rX',
    description: 'Tanenbaum takes a structured approach to explaining how networks work from the inside out. He starts with an explanation of the physical layer of networking, computer hardware and transmission systems; then works his way up to network applications. Tanenbaum\'s in-depth application coverage includes email; the domain name system; the World Wide Web (both client- and server-side); and multimedia (including voice over IP, Internet radio video on demand, video conferencing, and streaming media. Each chapter follows a consistent approach: Tanenbaum presents key principles, then illustrates them utilizing real-world example networks that run through the entire book—the Internet, and wireless networks, including Wireless LANs, broadband wireless and Bluetooth. The Fifth Edition includes a chapter devoted exclusively to network security. The textbook is supplemented by a Solutions Manual, as well as a Website containing PowerPoint slides, art in various forms, and other tools for instruction, including a protocol simulator whereby students can develop and test their own network protocols.',
    image: 'https://covers.zlibcdn2.com/covers299/books/c4/22/89/c422893549f0d1733d7d10daeb41f3bd.jpg',
  },
  // Networks

  // Information Systems
  {
    category: 'information systems',
    name: 'Management Information Systems: Managing the Digital Firm',
    author: 'Kenneth C. Laudon',
    year: '2019',
    pages: '660',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Rk6Z8b',
    buyLink: 'https://amzn.to/3mh5oOD',
    description: 'The authoritative, case-based study of IS in business today Management Information Systems: Managing the Digital Firm provides the most comprehensive overview of information systems used by business firms today, while drawing connections between MIS and business performance',
    image: 'https://covers.zlibcdn2.com/covers299/books/e1/34/c5/e134c58e6354f42a8dd498f1ea33ce10.jpg',
  },
  {
    category: 'information systems',
    name: 'Learning Agile: Understanding Scrum, XP, Lean, and Kanban',
    author: 'Andrew Stellman',
    year: '2014',
    pages: '420',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Fjk2o2',
    buyLink: 'https://amzn.to/3bSqH48',
    description: 'Agile has revolutionized the way teams approach software development, but with dozens of agile methodologies to choose from, the decision to "go agile" can be tricky. This practical book helps you sort it out, first by grounding you in agile’s underlying principles, then by describing four specific—and well-used—agile methods: Scrum, extreme programming (XP), Lean, and Kanban.',
    image: 'https://covers.zlibcdn2.com/covers299/books/24/79/f9/2479f9e08e9b3d454fa6791f58c174b6.jpg',
  },
  {
    category: 'information systems',
    name: 'Blockchain: Ultimate guide to understanding blockchain, bitcoin, cryptocurrencies, smart contracts and the future of money.',
    author: 'Mark Gates',
    year: '2017',
    pages: '125',
    format: 'PDF',
    downloadLink: 'https://bit.ly/32qbaFK',
    buyLink: 'https://amzn.to/33q3T81',
    description: '“On the internet, nobody knows you’re a dog.” - Peter Steiner On the blockchain, nobody knows you’re a fridge.” - Richard Gendal Brown Blockchain technology has been called the greatest innovation since the internet',
    image: 'https://covers.zlibcdn2.com/covers299/books/cd/42/16/cd4216e2f6cbba006e935566acd3e2c1.jpg',
  },
  // Information Systems

  // Operating systems
  {
    category: 'operating systems',
    name: 'Structured Computer Organization.',
    author: 'Andrew S. Tanenbaum',
    year: '2012',
    pages: '801',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3isNfuO',
    buyLink: 'https://amzn.to/3iv17F8',
    description: 'Structured Computer Organization, specifically written for undergraduate students, is a best-selling guide that provides an accessible introduction to computer hardware and architecture. This text will also serve as a useful resource for all computer professionals and engineers who need an overview or introduction to computer architecture',
    image: 'https://covers.zlibcdn2.com/covers299/books/0c/37/9a/0c379a31a38988e576779d2531b5dc3c.jpg',
  },
  {
    category: 'operating systems',
    name: 'Modern Operating Systems.',
    author: 'Andrew S. Tanenbaum',
    year: '2014',
    pages: '1137',
    format: 'PDF',
    downloadLink: 'https://bit.ly/32qFxfl',
    buyLink: 'https://amzn.to/3kjosdr',
    description: 'Modern Operating Systems, Fourth Edition, is intended for introductory courses in Operating Systems in Computer Science, Computer Engineering, and Electrical Engineering programs. It also serves as a useful reference for OS professionals',
    image: 'https://covers.zlibcdn2.com/covers299/books/15/6c/f9/156cf9f53cc80458097cebf1876be746.jpg',
  },
  // Operating systems

  // Management
  {
    category: 'management',
    name: 'Lean Six Sigma for Engineers and Managers: With Applied Case Studies.',
    author: 'Matthew J',
    year: '2015',
    pages: '232',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33oZTF4',
    buyLink: 'https://amzn.to/33ulrQs',
    description: 'An in-depth introduction, Lean Six Sigma for Engineers and Managers: With Applied Case Studies presents a detailed road map and industry examples to help you understand and implement the LSS system. It discusses the LSS process to define improvement needs, measure current business performance, analyze performance results using statistical tools.',
    image: 'https://covers.zlibcdn2.com/covers299/books/a4/2d/87/a42d87ab32fe4069a52e040dcc079d36.jpg',
  },
  {
    category: 'management',
    name: '100+ Management Models: How to Understand and Apply the World\'s Most Powerful Business Tools.',
    author: 'Fons Trompenaars',
    year: '2014',
    pages: '592',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mj7xt5',
    buyLink: 'https://amzn.to/35LptqH',
    description: 'An in-depth introduction, Lean Six Sigma for Engineers and Managers: With Applied Case Studies presents a detailed road map and industry examples to help you understand and implement the LSS system. It discusses the LSS process to define improvement needs, measure current business performance, analyze performance results using statistical tools.',
    image: 'https://covers.zlibcdn2.com/covers299/books/3b/2b/14/3b2b141e19be596287f6625798797bdc.jpg',
  },
  // Management

  // Marketing
  {
    category: 'marketing',
    name: 'Digital Marketing Strategy: An Integrated Approach to Online Marketing.',
    author: 'Fons Trompenaars',
    year: '2016',
    pages: '339',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3kfDZuu',
    buyLink: 'https://amzn.to/3hucOdR',
    description: 'Digital and social media are essential aspects of a marketing department\'s function; therefore, it is important that they are integrated into the organization\'s wider goals. Uniting digital marketing techniques with business strategy and established marketing models such as the 7 P\'s, Porter\'s Five Forces, and Customer Lifetime Value, author Simon Kingsnorth demonstrates how to formulate the best strategy for a company.',
    image: 'https://covers.zlibcdn2.com/covers299/books/21/cf/93/21cf93099295e5ddc80f16abfbc5fa8c.jpg',
  },
  {
    category: 'marketing',
    name: '400+ Essential Digital Marketing Tips for Your Business.',
    author: 'Ncube Mike.',
    year: '2015',
    pages: '124',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2ZA1u9K',
    buyLink: 'https://amzn.to/35Ag4SK',
    description: 'Get up to speed on the latest digital marketing tips, tricks, tactics and strategies with 400+ essential digital marketing tips, a resource for business owners and marketers that are looking to sharpen their digital skills and promote their businesses through channels like social media, pay per click advertising, organic search, affiliate marketing, email marketing and others.',
    image: 'https://covers.zlibcdn2.com/covers299/books/d6/b6/e7/d6b6e74afa72f4dc35abe0f8553df4ab.jpg',
  },
  {
    category: 'marketing',
    name: 'Consumerology: The Market Research Myth, the Truth About Consumers, and the Psychology of Shopping.',
    author: 'Philip Graves.',
    year: '2010',
    pages: '226',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3bWWTUa',
    buyLink: 'https://amzn.to/2Fr8saj',
    description: 'Market research is a myth. Philip Graves, one of the world\'s leading experts in consumer behaviour, reveals why the findings obtained from most market research are completely unreliable. Whether it is company executives seeking to define their corporate strategy or politicians wanting to understand the electorate, the idea that questions answered on a questionnaire or discussed in a focus group can provide useful insights on which to base business decisions is the cause of product failures, political blunders and wasted billions',
    image: 'https://covers.zlibcdn2.com/covers299/books/7d/3b/ee/7d3beeda77cfe679371d7732fdec74c1.jpg',
  },
  {
    category: 'marketing',
    name: 'The Brand Mapping Strategy: Design, Build, and Accelerate Your Brand.',
    author: 'Karen Leland.',
    year: '2016',
    pages: '224',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33phRal',
    buyLink: 'https://amzn.to/3mhxJ7q',
    description: 'Sharing hard-earned insights, advice, and best practices, brand and marketing strategist Karen Tiber Leland helps entrepreneurs, business owners, CEOs, and executives create a brand by design instead of default, gain greater influence in their industries and companies, and become thought leaders in their fields.',
    image: 'https://covers.zlibcdn2.com/covers299/books/71/6f/da/716fdae127b52ad557ad433187d86700.jpg',
  },
  // Marketing

  // Accounting
  {
    category: 'accounting',
    name: 'Principles of Corporate Finance.',
    author: 'Richard A Brealey.',
    year: '2016',
    pages: '997',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33p16fA',
    buyLink: 'https://amzn.to/3iwfrwX',
    description: 'The integrated solutions for Brealey\'s Principles of Corporate Finance have been specifically designed to help improve student performance, meaning that students are prepared for class and can successfully solve problems and analyse the results. Resources within Connect Finance provide unlimited opportunities for students to practice solving financial problems and apply what they\'ve learned. Brealey\'s world-leading content showing managers how to use financial theory to solve practical problems combined with a complete digital solution will help students achieve higher outcomes in the course.',
    image: 'https://covers.zlibcdn2.com/covers299/books/d3/ee/ed/d3eeed5dde92429f6075db956d5bf679.jpg',
  },
  {
    category: 'accounting',
    name: 'Financial Shenanigans: How to Detect Accounting Gimmicks and Fraud in Financial Reports',
    author: 'Howard M. Schilit.',
    year: '2018',
    pages: '336',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2DVB3Um',
    buyLink: 'https://amzn.to/2RnqKeZ',
    description: 'This fourth edition of the classic guide shines a light on the most shocking frauds and financial reporting offenders of the last twenty-five years, and gives investors the tools they need to detect: •Corporate cultures that incentivize dishonest practices•The latest tricks companies use to exaggerate revenue and earnings •Techniques devised by management to manipulate cash flow as easily as earnings•Companies that use misleading metrics to fool investors about their financial performance •How companies use acquisitions to hide deterioration in their underlying business This new edition focuses on the key case studies and most important lessons from the past quarter century, and brings you up to date on accounting chicanery in the global markets. Howard Schilit and his team of renowned forensic accounting experts expose financial reporting miscreants and unveil the latest methods companies use to mislead investors. You’ll learn everything you need to know to unearth deceptive reporting and avoid costly mistakes.',
    image: 'https://covers.zlibcdn2.com/covers299/books/97/f3/0b/97f30b94a74d1e0f32dbbc682ed7eedf.jpg',
  },
  {
    category: 'accounting',
    name: 'Accounting Principles',
    author: 'Jerry J. Weygandt.',
    year: '2015',
    pages: '1288',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2RuuCL3',
    buyLink: 'https://amzn.to/2Fuec2Z',
    description: 'The Twelfth Edition helps student get the most out of their accounting course by making practice simple. Both in the print text and online in WileyPLUS with ORION new opportunities for self-guided practice allow students to check their knowledge of accounting concepts, skills, and problem-solving techniques and receive personalized feedback at the question, learning objective, and course level',
    image: 'https://covers.zlibcdn2.com/covers299/books/c9/5f/b2/c95fb22faec57174d2922809cb20de2d.jpg',
  },
  // Accounting

  // Investing
  {
    category: 'investing',
    name: 'Investing For Dummies',
    author: 'Eric Tyson.',
    year: '2017',
    pages: '459',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2ZAAPcT',
    buyLink: 'https://amzn.to/35xMugt',
    description: 'In the world of investing, slow and steady wins the race. With this mantra in mind, trusted author and finance guru Eric Tyson is back with the latest edition of the #1 bestselling book, Investing For Dummies, to help you achieve your investment goals. Inside, he offers time-tested advice on how to develop a winning investment strategy that matches your abilities with your expectations — all the while ensuring you\'re slowly and steadily growing your portfolio.',
    image: 'https://covers.zlibcdn2.com/covers299/books/fc/a4/e7/fca4e78bd1cc279dceeccfcf9055e94e.jpg',
  },
  {
    category: 'investing',
    name: 'Economics for Investment Decision Makers: Micro, Macro, and International Economics.',
    author: 'Larry Harris.',
    year: '2013',
    pages: '800',
    format: 'PDF',
    downloadLink: 'https://bit.ly/32s5XgL',
    buyLink: 'https://amzn.to/3mj9lCn',
    description: 'Written by a distinguished academics and practitioners selected and guided by CFA Institute, the world’s largest association of finance professionals, Economics for Investment Decision Makers is unique in presenting microeconomics and macroeconomics with relevance to investors and investment analysts constantly in mind.',
    image: 'https://covers.zlibcdn2.com/covers299/books/be/fc/8c/befc8cb7a07a229b4bb8aa47f1f0adb9.jpg',
  },
  // Investing

  // Markets
  {
    category: 'markets',
    name: 'Guide to Financial Markets.',
    author: 'Marc Levinson.',
    year: '2014',
    pages: '306',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2FpTCRq',
    buyLink: 'https://amzn.to/3bVrj99',
    description: 'Extensively revised and updated following the fallout from the global financial crisis, the 6th edition of this highly regarded book brings the reader right up to speed with the latest financial market developments, and provides a clear and incisive guide to a complex world that even those who work in it often find hard to understand.',
    image: 'https://covers.zlibcdn2.com/covers299/books/37/60/0c/37600cd9bf40a47674f7c10a38d355f9.jpg',
  },
  {
    category: 'markets',
    name: 'Mapping the Markets: A Guide to Stock Market Analysis.',
    author: 'Robin Griffiths.',
    year: '2006',
    pages: '145',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3bZAwgL',
    buyLink: 'https://amzn.to/2FDyg2z',
    description: 'In this guide to stock market analysis, the authors offer a global overview of business cycles and their impact on financial markets, explain how stock markets are affected by the cycles and by seasonal and secular trends, and show readers how to identify sectors and stock in which to invest.',
    image: 'https://covers.zlibcdn2.com/covers299/books/c1/9e/23/c19e23d39a55f5d3caad035628f8f418.jpg',
  },
  // Markets

  // Econometrics
  {
    category: 'econometrics',
    name: 'Econometric Analysis.',
    author: 'William H. Greene.',
    year: '2018',
    pages: '1168',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3huRViB',
    buyLink: 'https://amzn.to/2ZzjMYC',
    description: 'In this guide to stock market analysis, the authors offer a global overview of business cycles and their impact on financial markets, explain how stock markets are affected by the cycles and by seasonal and secular trends, and show readers how to identify sectors and stock in which to invest.',
    image: 'https://covers.zlibcdn2.com/covers299/books/bd/14/fe/bd14fe167f36a77c54bfd33ca793cd76.jpg',
  },
  {
    category: 'econometrics',
    name: 'Financial Econometrics: From Basics to Advanced Modeling Techniques.',
    author: 'Svetlozar T. Rachev.',
    year: '2007',
    pages: '576',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33q2iPB',
    buyLink: 'https://amzn.to/35yecd1',
    description: 'Financial econometrics is a quest for models that describe financial time series such as prices, returns, interest rates, and exchange rates. In Financial Econometrics, readers will be introduced to this growing discipline and the concepts and theories associated with it, including background material on probability theory and statistics.',
    image: 'https://covers.zlibcdn2.com/covers299/books/0d/2a/e2/0d2ae2678621316d23a422f5d7201239.jpg',
  },
  // Econometrics

  // Algebra
  {
    category: 'algebra',
    name: 'A First Course in Abstract Algebra with Applications.',
    author: 'Joseph J. Rotman.',
    year: '2005',
    pages: '629',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mja3Q3',
    buyLink: 'https://amzn.to/3ivrA5f',
    description: 'This text introduces readers to the algebraic concepts of group and rings, providing a comprehensive discussion of theory as well as a significant number of applications for each.',
    image: 'https://covers.zlibcdn2.com/covers299/books/9f/33/aa/9f33aadcb6591cb3d8575e8f971a0131.jpg',
  },
  // Algebra

  // Linear Algebra
  {
    category: 'linear algebra',
    name: 'Introduction to Linear Algebra.',
    author: 'Gilbert Strang.',
    year: '2016',
    pages: '585',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2ZxB8oS',
    buyLink: 'https://amzn.to/3kcIczd',
    description: 'Linear algebra is something all mathematics undergraduates and many other students, in subjects ranging from engineering to economics, have to learn. The fifth edition of this hugely successful textbook retains all the qualities of earlier editions while at the same time seeing numerous minor improvements and major additions',
    image: 'https://covers.zlibcdn2.com/covers299/books/ca/5b/32/ca5b3224f7921f51b4f0cc081d0444c9.jpg',
  },
  {
    category: 'linear algebra',
    name: 'Linear Algebra For Dummies.',
    author: 'Mary Jane Sterling.',
    year: '2009',
    pages: '383',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3kj9ML1',
    buyLink: 'https://amzn.to/33u9cDL',
    description: 'I really like the approach of this book, as it uses good analogies, examples, graphs, and figures that appeal to your intuition to give deeper meaning to the subtleties of linear algebra. But it is a shame there are typos and mistakes. One in particular blew my mind - on p. 51 she states " A square matrix is singular if it has a multiplicative inverse; a matrix is non-singular if it does not have a multiplicative inverse." This is exactly opposite of how everyone else defines "singular", but she uses this definition consistently throughout the book, so either it\'s a mistake or she has decided to rewrite the rules of linear algebra. Either way, it\'s not helpful!!!',
    image: 'https://covers.zlibcdn2.com/covers299/books/09/7d/3e/097d3e1945b0bbda912bd8e429a47e00.jpg',
  },
  // Linear Algebra

  // Discrete Mathematics
  {
    category: 'discrete mathematics',
    name: 'Discrete Mathematics and Its Applications.',
    author: 'Mary Jane Sterling.',
    year: '2018',
    pages: '1118',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3bTCP57',
    buyLink: 'https://amzn.to/3bSEO9Q',
    description: 'Rosen\'s Discrete Mathematics and its Applications presents a precise, relevant, comprehensive approach to mathematical concepts. This world-renowned best-selling text was written to accommodate the needs across a variety of majors and departments, including mathematics, computer science, and engineering',
    image: 'https://covers.zlibcdn2.com/covers299/books/57/a3/cb/57a3cbe95c769f07e5aa01bb60210ac4.jpg',
  },
  {
    category: 'discrete mathematics',
    name: 'A Beginnes\'s Guide to Discrete Mathematics.',
    author: 'W. D. Wallis.',
    year: '2012',
    pages: '436',
    format: 'PDF',
    downloadLink: 'https://bit.ly/33to590',
    buyLink: 'https://amzn.to/2RqcP86',
    description: 'Wallis\'s book on discrete mathematics is a resource for an introductory course in a subject fundamental to both mathematics and computer science, a course that is expected not only to cover certain specific topics but also to introduce students to important modes of thought specific to each discipline',
    image: 'https://covers.zlibcdn2.com/covers299/books/24/b7/ce/24b7cefe0416b5afbe3c8dede783dc1e.jpg',
  },
  // Discrete Mathematics

  // Number Theory
  {
    category: 'number theory',
    name: 'Number Theory: A Problem-Solving Approach.',
    author: 'Titu Andreescu.',
    year: '2009',
    pages: '414',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mjrlNa',
    buyLink: 'https://amzn.to/3mhAh5u',
    description: 'Number theory, an ongoing rich area of mathematical exploration, is noted for its theoretical depth, with connections and applications to other fields from representation theory, to physics, cryptography, and more. While the forefront of number theory is replete with sophisticated and famous open problems, at its foundation are basic, elementary ideas that can stimulate and challenge beginning students. This lively introductory text focuses on a problem-solving approach to the subject.',
    image: 'https://covers.zlibcdn2.com/covers299/books/6c/64/79/6c6479b9a92d0ff27f7c9b69487eef60.jpg',
  },
  {
    category: 'number theory',
    name: 'An Introduction to the Theory of Numbers.',
    author: 'Godfrey Harold Hardy.',
    year: '2009',
    pages: '642',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3hwKNCi',
    buyLink: 'https://amzn.to/3hpRxBT',
    description: 'An Introduction to the Theory of Numbers by G. H. Hardy and E. M. Wright is found on the reading list of virtually all elementary number theory courses and is widely regarded as the primary and classic text in elementary number theory',
    image: 'https://covers.zlibcdn2.com/covers299/books/f4/1a/fc/f41afcb0b44dd6df662c40f9a302e6b4.jpg',
  },
  // Number Theory

  // Mathematicsematical Statistics
  {
    category: 'mathematicsematical statistics',
    name: 'Introduction to Mathematical Statistics.',
    author: 'Robert V. Hogg.',
    year: '2019',
    pages: '762',
    format: 'PDF',
    downloadLink: 'https://bit.ly/32pwFqg',
    buyLink: 'https://amzn.to/2Zz7NKU',
    description: 'Introduction to Mathematical Statistics by Hogg, McKean, and Craig enhances student comprehension and retention with numerous, illustrative examples and exercises. Classical statistical inference procedures in estimation and testing are explored extensively, and the text’s flexible organization makes it ideal for a range of mathematical statistics courses.',
    image: 'https://covers.zlibcdn2.com/covers299/books/a5/b9/41/a5b94141afa74508d2017b534d38f130.jpg',
  },
  {
    category: 'mathematicsematical statistics',
    name: 'Statistics for Dummies.',
    author: 'Deborah Rumsey.',
    year: '2003',
    pages: '326',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3k8ox3k',
    buyLink: 'https://amzn.to/3kcWqA8',
    description: 'In the numbers explosion all around us in our modern-day dealings, the buzzword is data, as in, “Do you have any data to support your claim?” “The data supported the original hypothesis that . . .” and “The data bear this out. . . .” But the field of statistics is not just about data. Statistics is the entire process involved in gathering evidence to answer questions about the world, in cases where that evidence happens to be numerical data.',
    image: 'https://covers.zlibcdn2.com/covers299/books/54/39/8e/54398ebee5eb061448a50100544497f6.jpg',
  },
  // Mathematicsematical Statistics

  // Analysis
  {
    category: 'analysis',
    name: 'Fourier analysis: an introduction.',
    author: 'Elias M. Stein.',
    year: '2003',
    pages: '326',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2DXX1pP',
    buyLink: 'https://amzn.to/35twzQm',
    description: 'This first volume, a three-part introduction to the subject, is intended for students with a beginning knowledge of mathematical analysis who are motivated to discover the ideas that shape Fourier analysis. It begins with the simple conviction that Fourier arrived at in the early nineteenth century when studying problems in the physical sciences--that an arbitrary function can be written as an infinite sum of the most basic trigonometric functions.',
    image: 'https://covers.zlibcdn2.com/covers299/books/92/58/95/925895af1a0a8cba1ac246a974376622.jpg',
  },
  {
    category: 'analysis',
    name: 'Problems and Solutions in Real Analysis.',
    author: 'Masayoshi Hata.',
    year: '2007',
    pages: '292',
    format: 'PDF',
    downloadLink: 'https://bit.ly/32rgyIx',
    buyLink: 'https://amzn.to/35uOOF7',
    description: 'This unique book provides a collection of more than 200 mathematical problems and their detailed solutions, which contain very useful tips and skills in real analysis. Each chapter has an introduction, in which some fundamental definitions and propositions are prepared. This also contains many brief historical comments on some significant mathematical results in real analysis together with useful references.',
    image: 'https://covers.zlibcdn2.com/covers299/books/f9/04/4e/f9044e52243718f43e6762d722a07474.jpg',
  },
  {
    category: 'analysis',
    name: 'Real Analysis.',
    author: 'Halsey Royden Hata.',
    year: '2007',
    pages: '292',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2ZADiUH',
    buyLink: 'https://rb.gy/opujcm',
    description: 'Real Analysis, Fourth Edition, covers the basic material that every reader should know in the classical theory of functions of a real variable, measure and integration theory, and some of the more important and elementary topics in general topology and normed linear space theory. This text assumes a general background in mathematics and familiarity with the fundamental concepts of analysis',
    image: 'https://covers.zlibcdn2.com/covers299/books/46/7a/74/467a74bdde78cd0e1f9e470b01423b03.jpg',
  },
  // Analysis

  // Creative Thinking
  {
    category: 'creative thinking',
    name: 'Smart Thinking: Skills for Critical Understanding and Writing.',
    author: 'Matthew Allen.',
    year: '2005',
    pages: '207',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Fw1QHx',
    buyLink: 'https://amzn.to/3kjgZen',
    description: 'Smart Thinking: Skills for Critical Understanding and Writing 2E is a practical step-by-step guide to improving skills in analysis, critical thinking, and the effective communication of arguments and explanations.',
    image: 'https://covers.zlibcdn2.com/covers299/books/a3/45/9c/a3459c403398638208308d220747d6c5.jpg',
  },
  {
    category: 'creative thinking',
    name: 'The Art of Creative Thinking: How to Be Innovative and Develop Great Ideas.',
    author: 'John Adair.',
    year: '2009',
    pages: '145',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mkZD2w',
    buyLink: 'https://amzn.to/3bZBPMW',
    description: 'The Art of Creative Thinking provides clear, practical guidelines for developing your powers as a creative thinker. Using examples of entrepreneurs, authors, scientists and artists, John Adair illustrates a key aspect of creativity in each chapter.',
    image: 'https://covers.zlibcdn2.com/covers299/books/7f/5e/2f/7f5e2f8d04ef54a498c52bae280117c7.jpg',
  },
  {
    category: 'creative thinking',
    name: '101 Creative Problem Solving Techniques: The Handbook of New Ideas for Business.',
    author: 'James M. Higgins.',
    year: '1994',
    pages: '241',
    format: 'PDF',
    downloadLink: 'https://bit.ly/32pO2r0',
    buyLink: 'https://amzn.to/3iudiBR',
    description: 'This practical, easy and fun to read book describes 101 creative ways to solve problems. It is designed for individuals and groups. This book is artfully and humorously illustrated. Descriptions of the techniques contain examples of their usage across a wide diversity of companies. Problem solving is a skill that is not taught in schools but is vital to living and working with others. Everyone should have this handy little book available at all times.',
    image: 'https://covers.zlibcdn2.com/covers299/books/d6/31/e4/d631e4b4dcd70843e575c31f448f07fd.jpg',
  },
  // Creative Thinking

  // The art of communication
  {
    category: 'the art of communication',
    name: 'How To Analyze People:',
    author: 'James M. Higgins.',
    year: '2019',
    pages: '124',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Rlmj4t',
    buyLink: 'https://amzn.to/2FCUG4k',
    description: '*Let\'s be honest...  even just for once you have dreamed of having all of your relations in the palm of your hand, realizing your partner\'s desire before he asks anything, or smelling the cheating in the air. But if you lack of control makes you feel helpless and powerless, then it\'s time to wake up and learn how to turn things around. It\'s time to stop being slave of other\'s business and make the world play your game by your rules',
    image: 'https://covers.zlibcdn2.com/covers299/books/54/56/85/545685becb9edbc4ffc28004dafda2fe.jpg',
  },
  // The art of communication

  // Communication
  {
    category: 'communication',
    name: 'Communication Theory: Media, Technology and Society',
    author: 'David Holmes.',
    year: '2005',
    pages: '272',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mj3ywx',
    buyLink: 'https://amzn.to/3kgUlTS',
    description: 'This book offers an introduction to communication theory that is appropriate to our post-broadcast, interactive media environment. The author contrasts the "first media age" of broadcast with the "second media age" of interactivity. Communication.',
    image: 'https://covers.zlibcdn2.com/covers299/books/7c/e1/e0/7ce1e0492d89bdee34343ad8405f6215.jpg',
  },
  {
    category: 'communication',
    name: 'Communication Systems',
    author: 'Simon Haykin.',
    year: '2000',
    pages: '838',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mhAJ3H',
    buyLink: 'https://amzn.to/33p7uDn',
    description: 'This book offers an introduction to communication theory that is appropriate to our post-broadcast, interactive media environment. The author contrasts the "first media age" of broadcast with the "second media age" of interactivity. Communication.',
    image: 'https://covers.zlibcdn2.com/covers299/books/a2/21/4c/a2214c443700c0981c542e55626aa472.jpg',
  },
  // Communication

  // Electronics
  {
    category: 'electronics',
    name: 'Make: Electronics: Learning Through Discovery',
    author: 'Charles Platt.',
    year: '2015',
    pages: '352',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Rq0C32',
    buyLink: 'https://amzn.to/3bXVJba',
    description: '"A fabulous book: well written, well paced, fun, and informative. I also love the sense of humor. It\'s very good at disarming the fear. And it\'s gorgeous. I\'ll be recommending this book highly."',
    image: 'https://covers.zlibcdn2.com/covers299/books/70/7d/5b/707d5b2361f8ce358156484fb4e2514a.jpg',
  },
  {
    category: 'electronics',
    name: 'Electronics All-in-One For Dummies',
    author: 'Doug Lowe.',
    year: '2017',
    pages: '960',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2DXrmVu',
    buyLink: 'https://amzn.to/3iusBut',
    description: 'If you know a breadboard from a breadbox but want to take your hobby electronics skills to the next level, this is the only reference you need. Electronics All-in-One For Dummies has done the legwork for you — offering everything you need to enhance your experience as an electronics enthusiast in one convenient place.',
    image: 'https://covers.zlibcdn2.com/covers299/books/d9/da/9e/d9da9eb1813525efc4c1c2702d618b98.jpg',
  },
  // Electronics

  // Nanotechnology
  {
    category: 'nanotechnology',
    name: 'Nanoparticles: From Theory to Application',
    author: 'Günter Schmid.',
    year: '2010',
    pages: '538',
    format: 'PDF',
    downloadLink: 'https://bit.ly/2Fisfc7',
    buyLink: 'https://amzn.to/3hsRLYY',
    description: 'Offers an introduction to the science of nanoparticles, from fundamental principles to their use in novel applicationsThe second edition is completely revised, updated and enlarged and includes four new chaptersIncludes numerous examples from the recent literature - this is a prime reference for chemists and materials scientists working with and developing nanoparticle systems',
    image: 'https://covers.zlibcdn2.com/covers299/books/0a/6d/98/0a6d989dba4f5d5921093d2f412861ab.jpg',
  },
  {
    category: 'nanotechnology',
    name: 'Introduction to Nanoscience and Nanotechnology',
    author: 'Chris Binns.',
    year: '2010',
    pages: '319',
    format: 'PDF',
    downloadLink: 'https://bit.ly/3mivukg',
    buyLink: 'https://amzn.to/3mhBTw5',
    description: 'Introduction to Nanoscience and Nanotechnology explains nanotechnology to an audience that does not necessarily have a scientific background. It covers all aspects, including the new areas of biomedical applications and the use of nanotechnology to probe the "quantum vacuum." After discussing the present state of the art in nanotechnology, the book makes estimates of where these technologies are going and what will be possible in the future.',
    image: 'https://covers.zlibcdn2.com/covers299/books/69/59/83/695983dd26198b9e4d5dfb3c0cce8afa.jpg',
  },
  // Nanotechnology
];
